### ISSUE TITLE
Remove imagestatus CR

### ISSUE THREAD

**Issue by cpuguy83** [eraser-dev/eraser#102]
`ImageStatus` adds a lot of overhead to running eraser for mostly low-value information.
The intention of this was to have a sort of audit trail as to what happened. It doesn't exactly work that way because details get overwritten and other things related to the implementation, but the intention is to know exactly what happened during a run.

Instead we can change our job deletion strategy with the intention of keeping pods for jobs around longer to ensure pod logs are kept around for a period of time for debugging purposes.
Additionally we should make sure that we log everything an eraser pod does to stdout.

Related #96

**Comment by sozercan** [comment]
- [ ] remove CR imagestatus and imagelist.status
- [ ] output logs (status, image name, reason, node name) from eraser pods 
- [ ] configurable deletion timestamp for jobs
