### ISSUE TITLE
[BUG] wrong defaults in the helm chart docs

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#1032]
### Version of Eraser

n/a

### Expected Behavior

```
runtimeConfig.components.collector | Settings for the collector component. | { enabled: true }
-- | -- | --
runtimeConfig.components.scanner | Settings for the scanner component. | { enabled: true }
```

https://github.com/eraser-dev/eraser/blob/main/charts/eraser/values.yaml#L39-L50

since this is generated actual change needs to be in: https://github.com/eraser-dev/eraser/blob/main/third_party/open-policy-agent/gatekeeper/helmify/static/README.md

### Actual Behavior

helm chart docs have the wrong defaults for collector and scanner. we should also check if anything else has the wrong defaults
https://github.com/eraser-dev/eraser/blob/main/charts/eraser/values.yaml#L39-L50

```
runtimeConfig.components.collector | Settings for the collector component. | { enabled: false }
-- | -- | --
runtimeConfig.components.scanner | Settings for the scanner component. | { enabled: false }
```

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by akhilsaivenkata** [comment]
Hi @sozercan , Its also mentioned that we need to check if anything else has the wrong defaults in that file. So what is the source of truth to validate? does official documentation works?

**Comment by sozercan** [comment]
@akhilsaivenkata thanks for checking! source of truth is https://github.com/eraser-dev/eraser/blob/main/third_party/open-policy-agent/gatekeeper/helmify/static/values.yaml which generates https://github.com/eraser-dev/eraser/blob/main/charts/eraser/values.yaml
