### ISSUE TITLE
[BUG] Unnecessary permissions

### ISSUE THREAD

**Issue by echoounlimited** [eraser-dev/eraser#1036]
### Version of Eraser

1.3.1

### Expected Behavior

The Deployment [eraser-controller-manager](https://github.com/eraser-dev/eraser/blob/main/charts/eraser/templates/eraser-controller-manager-deployment.yaml) in the charts has `delete` verb of the `pods` resource ([eraser-manager-role-clusterrole.yaml](https://github.com/eraser-dev/eraser/blob/main/charts/eraser/templates/eraser-manager-role-clusterrole.yaml)). However, after reading the source code of [eraser](https://github.com/eraser-dev/eraser), I didn't find any Kubernetes API usages that require this permission.Therefore, for security reasons, I suggest checking this permission to determine if it is truly unnecessary. If it is, the issue should be fixed by removing the unnecessary permission or other feasible methods. 

### Steps To Reproduce

Use helm chart with default values.

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by ashnamehrotra** [comment]
Hi @Yseona thank you for raising this! Pod permissions were removed in #956. Since this was cherry-picked into v1.3.0 for a v1.3.1 patch release, the changes from `manifest_staging/charts/..` were not reflected into `charts/...`. This will be fixed in the next minor release.

cc @sozercan

**Comment by macetw** [comment]
Suggest closing this issue if it is truly resolved.

**Comment by sozercan** [comment]
@ashnamehrotra are you good to close this?

**Comment by ashnamehrotra** [comment]
@sozercan yes, this can be closed now!
