### ISSUE TITLE
[REQ] Publish on ArtifactHub

### ISSUE THREAD

**Issue by framctr** [eraser-dev/eraser#1046]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

Publish Eraser Helm chart in [ArtifactHub.io](https://artifacthub.io/).

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
Added the chart to AF, it should be visible shortly

https://artifacthub.io/packages/helm/eraser/eraser
