### ISSUE TITLE
host helm repo in github pages

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#108]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
After #77, chart should be hosted in github pages

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

see comment below for examples

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by sozercan** [comment]
in the release stage: https://github.com/open-policy-agent/gatekeeper/blob/master/.github/workflows/workflow.yaml#L406-L412

use action https://github.com/stefanprodan/helm-gh-pages

**Comment by joheec** [comment]
I can take this!!!

**Comment by joheec** [comment]
Please assign me. Thank you!
