### ISSUE TITLE
Parallelize tests

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#139]
**Describe the solution you'd like**
Run the tests in parallel, for improved isolation (create a new cluster for each test) and performance.

**Anything else you would like to add:** 

**Environment:**

- Eraser version: v0.1.0
- Kubernetes version: (use `kubectl version`): N/A

**Comment by olasowemimo** [comment]
Should running the test in multiple clusters be the goal or we could target some test methods by tags and run these tests in parallel or run the test on different environments?
