### ISSUE TITLE
add a pipeline to scan for vuln as a pr gate

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#152]
**Describe the solution you'd like**
pr gate pipeline that scans the binary and image to make sure pr is not introducing any known vulnerabilities

example: https://github.com/open-policy-agent/gatekeeper/blob/e71351d0672f8d0143b9df6d23d540928a9ddb74/.github/workflows/workflow.yaml#L244-L272

**Comment by irenestanely** [comment]
@sozercan Do we need this scan as part of test.yaml or release.yaml pipeline? I believe its test.yml right?

**Comment by sozercan** [comment]
@irenechristopher that's correct, as part of test.yaml
