### ISSUE TITLE
Parallelize scanning workload

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#159]
**Describe the solution you'd like**
As work progresses on scanning, we will need to think about how to divide up the scanning workload.  For example, in situations where there are a very large number of nodes.

**Anything else you would like to add:**
A few thoughts:
- It is possible to divide the workflow in arbitrary ways, such as `len(images)/len(pods)` images scheduled for each pod, with several pods taking on a portion of the workload.
- A single-publisher, multiple-consumer model whereby workers pull from a work queue when they are ready.
  - Workers can be individual pods, or goroutines in a single pod. Unclear at this point which is better.
  - Still unclear how the queueing mechanism would work. Could the queueing be managed by kubernetes (ideal), or would we need some external queue (rabbitMQ) or similar (less ideal)?
  - More efficient than the arbitrary method, but introduces complexities.

**Environment:**
Not relevant

**Comment by sozercan** [comment]
Fixed in #339
