### ISSUE TITLE
Decide how to handle nameless images

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#160]
**Describe the solution you'd like**
Some images are known only by their digest, with no repository (name) information. Trivy can scan an image by digest 
- if the image is present locally in a docker cache
- if the image is present locally in a podman cache
- if enough information is present such that trivy can pull from a remote repository, ex `trivy image docker.io/library/nginx@sha256:61face6bf030edce7ef6d7dd66fe452298d6f5f7ce032afdd01683ef02b2b841`

**Anything else you would like to add:**
One possible (but expensive) solution is to push nameless images, by digest, to an internal-to-cluster registry, and then use trivy to scan the registry. The registry would be given a TTL and cleaned up. There are two major downsides to this:
- Pushing is an expensive operation
- The CRI has no push operation, so we would need to drop down below the CRI layer

**Comment by sozercan** [comment]
Today, we delete unscannable images if `--delete-scan-failed-images` is enabled (if image doesn't exist publicly or it's just a digest)
If there's demand for scanning nameless images, one possible option is to collect and scan in the same pod.

**Comment by cpuguy83** [comment]
I think this issue will be resolved with the scanner redesign?

**Comment by sozercan** [comment]
@cpuguy83 that's correct.

**Comment by sozercan** [comment]
Fixed in #339
