### ISSUE TITLE
add helm upgrade test to ci

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#168]
**Describe the solution you'd like**
after #108 is merged,
test that installs helm chart using a specific version then upgrades to latest chart is `manifest_staging`

example: https://github.com/open-policy-agent/gatekeeper/blob/master/.github/workflows/upgrade.yaml

**Comment by lee0c** [comment]
@sozercan Should this run e2e tests, or just deploy the Helm chart then upgrade? Right now the e2e tests looked to be pretty reliant on a YAML deployment of Eraser.

If the upgrade is successful, should this workflow promote the helm chart from staging to the charts dir? Or will that be a manual step?

**Comment by lee0c** [comment]
Also, you can assign me or @joheec

**Comment by sozercan** [comment]
this is for testing if a PR breaks compatibility with a previous Helm chart version. Once we release a tagged release and helm chart is available in the helm repo, this PR test should:

- deploy a chart from helm repo (#108), it's pinned to a specific version (base helm version that comes from Makefile). this is the version we want to be backwards compatible
- optionally, run tests
- upgrade the helm chart version using chart in `manifest_staging` in the PR
- run tests 

example: https://github.com/open-policy-agent/gatekeeper/blob/master/.github/workflows/upgrade.yaml

**Comment by sozercan** [comment]
@lee0c i also opened #199 for a regular helm test

**Comment by lee0c** [comment]
@sozercan Has a chart been published to the github pages repo yet? To fully build this out that is required.

**Comment by sozercan** [comment]
not yet, that will require a new release to be cut. #199 might be easier one to get started with
