### ISSUE TITLE
Have Eraser clean up all images except for a specified list

### ISSUE THREAD

**Issue by salaxander** [eraser-dev/eraser#174]
I've heard from a couple folks that they would like the option to invert the logic of an `ImageList` and provide a list of images that ***should not*** be cleaned up, and have Eraser target all other images. 

I imagine this could either be implemented as a separate resource (i.e. `AllowedImageList`) or be based off a field on the existing `ImageList` resource.

**Comment by sozercan** [comment]
@salaxander is this duplicate of https://github.com/Azure/eraser/issues/29

**Comment by salaxander** [comment]
ah yes, my mistake! I'll close this one and add #29 to my notes. Thanks for pointing that out!
