### ISSUE TITLE
add codecov action

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#198]
**Describe the solution you'd like**
add an action to visualize code coverage for a pr

example: https://github.com/open-policy-agent/gatekeeper/blob/master/.github/workflows/workflow.yaml#L78-L83

**Comment by kitarp29** [comment]
Hi @sozercan 
I am interested in solving this issue.
I have very less clue to resolve this issue.
But with a little help and guidance I am sure I can resolve it.
