### ISSUE TITLE
add helm test to ci

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#199]
**Describe the solution you'd like**
after #77 is merged, we should add a e2e test

**Comment by anmalkov** [comment]
@sozercan could you please explain what should be exactly tested here? Thx

**Comment by sozercan** [comment]
same test as we have today, but for helm. we want this to be a parallel test (a new job - `helm-e2e-test`) so it doesn't consume extra time

something like:
```
helm install manifest_staging/charts/eraser ... --wait
make e2e-test
```

https://github.com/Azure/eraser/blob/main/.github/workflows/test.yaml#L105

**Comment by lee0c** [comment]
@sozercan Just to confirm - currently the e2e-test involves deployment of the eraser YAML. It looks like your concept of the helm version would not handle the deployment of the helm chart, but just the testing. Should then the current e2e-test have two modes, one which installs via plain YAML and one which doesn't install anything but relies on the installation already existing?

**Comment by anmalkov** [comment]
@sozercan @lee0c I think it might be a good idea to check that it's already deployed or not in code (by checking the existence of the namespace or the manager pod in a cluster). If it's already there - no deployment executed in e2e tests. 
Another thing - I think it will be better to use the helm chart for all of e2e tests instead of a yaml manifest.

**Comment by sozercan** [comment]
i didn't realize `make e2e-test` is actually hardcoded to use the eraser.yaml. Sounds like we need to separate out the logic for just running e2e

Can you check if there a way to run `eraser_test.go` seperately?

**Comment by sozercan** [comment]
> Another thing - I think it will be better to use the helm chart for all of e2e tests instead of a yaml manifest.

I think we should test both in parallel since helm has it's own generation logic that might be broken vs yaml's generation logic

**Comment by lee0c** [comment]
@sozercan so I think the issue we will run into is that `main_test.go` has the logic to create the Kind cluster onto which everything is deployed, so it's hard to skip. That also introduces an issue to @anmalkov 's plan as we'd need to start the cluster (and therefore start the tests) prior to deployment.

Should we work on decoupling cluster creation/yaml deployment from testing? That seems like it would benefit all use cases by making code and cluster creation more reusable.

**Comment by sozercan** [comment]
@helayoty any thoughts? since you added the `main_test.go`

**Comment by helayoty** [comment]
@sozercan  @lee0c  

[Here](https://github.com/kubernetes-sigs/scheduler-plugins/pull/349/files#diff-345f4ae23b0645edf99172a04da688e38f03f0e398ca32ec3905d4ecc325cdcc) is a sample PR of how to deploy a helm chart that we need to have before any test starts after creating a kind cluster using `e2e framework`

Another Sample [here](https://github.com/kubernetes-sigs/e2e-framework/tree/main/examples/third_party_integration/helm) on how to deploy helm chart for any other reason (Redis, Nginx , DB, etc... )

**Comment by lee0c** [comment]
@helayoty I guess that answers it, we will put the helm deployment into the testing code! Thank you for the pointers 😄

**Comment by pmengelbert** [comment]
@sozercan do we actually need this anymore? We are now using helm for all of the e2e tests anyway

**Comment by sozercan** [comment]
@pmengelbert yea i think we can close this. do we have any tests that tests yaml?
