### ISSUE TITLE
Parallel image cleaning

### ISSUE THREAD

**Issue by eedorenko** [eraser-dev/eraser#203]
- Create Nginx and Redis deployment
- Delete Nginx and Redis deployment
- Start cleaning Nginx image
- Start cleaning Redis image before Nginx cleaning ends
- Make sure Nginx and Redis images are cleaned

Result: both images Nginx and Redis are cleaned successfully, but the first imagejob (nginx) and corresponding completed eraser pods are not deleted. 

The bug is reproducible by `deleteImagesParallel` test from #201 PR.

**Comment by pmengelbert** [comment]
@eedorenko Thank you for pointing this out! PRs #204 and #205 are the first steps toward addressing this.

Probably the best option is to delete the ImageJob (which will also terminate the eraser pods) on ImageList update events, then create a new one, which will respond to the new list.
