### ISSUE TITLE
Arguments to Eraser

### ISSUE THREAD

**Issue by ashnamehrotra** [eraser-dev/eraser#208]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- [x] Pass in repeat period
- [x] scanner image as arguments to Eraser for ImageCollector Controller.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
This will be resolved by #234
