### ISSUE TITLE
ImageCollector Controller - Scanner part

### ISSUE THREAD

**Issue by ashnamehrotra** [eraser-dev/eraser#209]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Once shared image collector CR is created, scanner should begin and update the Status field of the CR with images that were found vulnerable.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
This was completed by #173
