### ISSUE TITLE
Trivy scanner: Allow pull secrets

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#215]
**Describe the solution you'd like**
Some images will not be known to the Trivy scanner. In order to resolve images unknown to the Trivy database, it tries to pull in the images, first using a docker or podman daemon. If that action fails, Trivy will attempt to pull the image by HTTP. In any case, the container will need access to a registry pull secret in the `eraser-system` namespace.

**Environment:**
N/A

**Comment by sozercan** [comment]
We should discuss having pull secrets vs running a scanner per node. Related #160

**Comment by sozercan** [comment]
No longer needed with #339
