### ISSUE TITLE
add collector and scanner to trivy pr scan

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#233]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Fixed in https://github.com/Azure/eraser/pull/229

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
this will be resolved by #229
