### ISSUE TITLE
Address potential for exceeding etcd size limits on large clusters

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#240]
**Describe the solution you'd like**
The limit on custom resources, such as `imagelist` and `imagecollector` is 1.5MB. On very large clusters, we could exceed that limit.

For each image, there is a digest and a name. The digest is 68 bytes, and the name is ~256 bytes (128 for tag according to the spec, and this calculation assumes a repo name of the same length). Total is 324 bytes.

1.5 * 2^20 / 324 = ~4854 images. If every image is both unique and vulnerable, then each will appear twice in an imagecollector, leaving us with space to consider ~2427 images. To be on the safe side, let's say 2,000 as the upper limit.

With very large clusters, we will need an alternative solution. A couple of ideas that have been presented are:
- Collect and scan in one operation, which also creates the imagelist, removing the need for the images to be recorded in a custom resource
- Implement some sort of work-queue to hold the workload. This is related to #159

**Comment by salaxander** [comment]
Closing with recent changes
