### ISSUE TITLE
customizable severity for scanner job

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#242]
**Describe the solution you'd like**
ability to customize severity on scanner job https://github.com/Azure/eraser/blob/main/controllers/imagecollector/imagecollector_controller.go#L419

**Comment by pmengelbert** [comment]
@sozercan There are several scanner flags that we need to be able to "pass through", from the manager flags to scanner flags. We can do them one by one, but it may be better to allow multiple `--scanner-arg` flags on the manager, which get passed through to the scanner. For example:
`--scanner-arg=--severity=CRITICAL,HIGH,MEDIUM --scanner-arg=--ignore-unfixed=false` would pass through both `--severity` and `--ignore-unfixed`.

Currently only part of the scanner's CLI flag API surface is exposed to the manager (and thus the user)

**Comment by sozercan** [comment]
@pmengelbert i like that idea!
