### ISSUE TITLE
allow list for images and registries we don't want to remove

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#29]
This can be done either as part of scanner, imagelist, or eraser

we can have a configmap that defines images to be in allow list (never remove even if they are vulnerable, etc)

- exclude specific images and tags (`'myregistry.azurecr.io/myImage:tag`)
- exclude all images in a registry (i.e., `myregistry.azurecr.io/*`)

**Comment by jasonzio** [comment]
As a safety measure, you could check to make sure this "suppress erasure" list doesn't get stale by requiring the last-modified date to be within minutes or hours of the newest (least recently modified) actively running container; essentially, you'd require anyone using this list to deploy an updated list any time they updated any container.
