### ISSUE TITLE
exclustion configmap supports multiple config

### ISSUE THREAD

**Issue by jiashun0011** [eraser-dev/eraser#338]
To integrate Eraser on AKS, we want to keep some pre-defined system-level images in exclusion list and allow clients to define their ones in another configmap at the same time.

By searching the code base, looks like the exclusion configmap is now only loaded from `/run/eraser.sh/excluded/excluded`. 

Is this possible to support multiple exclusion configmap in future?

**Comment by sozercan** [comment]
I was thinking we can have exclusion list based on predefined labels so users can define any configmap in the eraser namespace to be an exclusion list
