### ISSUE TITLE
exclusion configmap support user-defined name

### ISSUE THREAD

**Issue by jiashun0011** [eraser-dev/eraser#349]
Currently, the exclusion list is hardcoded as `excluded`.

```
kubectl create configmap excluded --from-file=excluded=sample.json --namespace=eraser-system
```

Can we extend it with user-defined name?

**Comment by jiashun0011** [comment]
Related issue: [exclustion configmap supports multiple config #338](https://github.com/Azure/eraser/issues/338).

**Comment by sozercan** [comment]
@jiashun0011 closing this issue. As mentioned in https://github.com/Azure/eraser/issues/338#issuecomment-1197320232, we'll use configmap labels to mark exclusion lists so they can be any name
