### ISSUE TITLE
add metrics

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#38]
we need to define what metrics makes most sense and add metrics support
also, this will be unauth endpoint so we don't want to provide any private information

https://opentelemetry.io/

**Comment by sozercan** [comment]
revert #36 once we have this

**Comment by ashnamehrotra** [comment]
https://docs.google.com/document/d/1-xgzuL96WI6T3X7Nalsyw9k3cUTX8UEehCs9GHNEdY0/edit

**Comment by sozercan** [comment]
@ashnamehrotra looks like doc is private

**Comment by ashnamehrotra** [comment]
fixed the permissions!

**Comment by sozercan** [comment]
example: https://github.com/Azure/azure-workload-identity/pull/478
