### ISSUE TITLE
add architecture diagram

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#399]
**Describe the solution you'd like**
add an architecture diagram

we have a few old ones here: https://docs.google.com/document/d/1Rz1bkZKZSLVMjC_w8WLASPDUjfU80tjV-XWUXZ8vq3I/edit#heading=h.bbpo3iwqk0xy

old draw.io diagrams:
https://drive.google.com/file/d/1sXrFWtdbWPrPSzT94aXpsXTc0fg-dFnF/view?usp=sharing
https://drive.google.com/file/d/1L_wDwU9zKaLuv5qBmoTiYx4NUqForUL-/view?usp=sharing

**Comment by pmengelbert** [comment]
@sozercan do we want this on the README? the website?
