### ISSUE TITLE
add CI for e2e tests

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#4]
runs e2e tests using [kind](https://github.com/kubernetes-sigs/kind)

**Comment by sozercan** [comment]
- create kind cluster with multiple nodes 
- `kind load` a test image
- create ImageList object with the test image
- check if pods are scheduled on all nodes (nodes could be unschedulable or pods might have high requests so they don't get scheduled)
- check if pods are complete
- when finished, check if test image is removed

**Comment by helayoty** [comment]
@sozercan  Do you mind if I use the e2e-framework to build the e2e tests? 
Also, the issue description for CI but your comments for building the tests, is that right?
