### ISSUE TITLE
Using MCR registry-based images in Eraser

### ISSUE THREAD

**Issue by shantanuchaudhary24** [eraser-dev/eraser#402]
**Describe the solution you'd like**
When we deploy Eraser to our AKS clusters, we expect the Eraser pods to pull images from MCR based registry and not GHCR. This is because Microsoft services must use compliant images hosted in MCR registry.

**Anything else you would like to add:**
We see that images used in collector, trivy-scanner, eraser containers are all GHCR based.

**Environment:**
Pre-production, Azure Public Cloud

- Eraser version: 0.4.0
- Kubernetes version: 1.23

**Comment by sozercan** [comment]
@shantanuchaudhary24 If you are using the AKS add-on, they will be updated to images from MCR on the AKS side. Closing this issue as this on AKS-specific issue.

cc @jiashun0011
