### ISSUE TITLE
What is the difference from the Kubelet GC?

### ISSUE THREAD

**Issue by fernandorubbo** [eraser-dev/eraser#440]
Not a bug, it is a question:

What is the difference from what Kubelet gc does?
https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images

It says in the k8s page:
The [kubelet](https://kubernetes.io/docs/reference/generated/kubelet) performs garbage collection on unused images every five minutes and on unused containers every minute. You should avoid using external garbage collection tools, as these can break the kubelet behavior and remove containers that should exist.

**Comment by pmengelbert** [comment]
@fernandorubbo One of the advantages of Eraser is that it can conditionally remove images based on the results of vulnerability scans

**Comment by fernandorubbo** [comment]
Got it. Thank you very much.

**Comment by pmengelbert** [comment]
Also, kubelet does gc by disk pressure, but eraser gives finer-grained controls over removal and offers removal on-demand.
