### ISSUE TITLE
Rename `collector` pod and controller

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#453]
**Anything else you would like to add:**
The `collector` pod is no longer an accurate name for what it does, because it collects, scans, and erases. It also creates ambiguity between the `collector` pod vs the container with the same name.

Possible: 
~- `ImageCollector` CR -> `ImageFilter` CR~
~- `ImageCollector` Controller -> `ImageFilter` Controller~
- `collector` pod -> `filter` pod
- `collector` container -> stays `collector` container

**Environment:**
- Eraser version: **v0.4.0**

**Comment by pie-r** [comment]
Would it be possible to have this in a next release?
@salaxander

**Comment by sozercan** [comment]
some ideas:
- processor
- executor
- pipeline
- runner

after discussion with the maintainers, we are going with: renaming `eraser` container to `remover` (for both manual and automated runners) and renaming `collector` to `eraser`.
This will align on `eraser` as the name for both the manual process and the automated process runner.

@pie-r let us know if you have any thoughts on the above path forward.

**Comment by pie-r** [comment]
> some ideas:
> 
> * processor
> * executor
> * pipeline
> * runner
> 
> after discussion with the maintainers, we are going with: renaming `eraser` container to `remover` (for both manual and automated runners) and renaming `collector` to `eraser`. This will align on `eraser` as the name for both the manual process and the automated process runner.
> 
> @pie-r let us know if you have any thoughts on the above path forward.

I like the renaming proposal. Maybe it could make sense to have `eraser` and `eraser-manual` to distinguish between manual/automated and track better who is doing what.  But from the architecture diagram it seems not easily possible (I don't know if there is already a specific label to distinguish them).

Do you plan to update also ~~`Image: mcr.microsoft.com/oss/eraser/collector:v1.0.0` from `collector` -> `eraser`~~
`Image: mcr.microsoft.com/oss/eraser/eraser:v1.0.0` from `eraser` -> `remover`
? 

As a reference now the pods are using those repositories:
```
Image:         mcr.microsoft.com/oss/eraser/collector:v1.0.0
Image:         mcr.microsoft.com/oss/eraser/eraser:v1.0.0
Image:         mcr.microsoft.com/oss/eraser/eraser-trivy-scanner:v1.0.0
```

Just for consistency there are also those two images to refresh :D
https://azure.github.io/eraser/docs/architecture#manual-image-cleanup

**Comment by sozercan** [comment]
@pie-r i think we can add a label to it if it's manually triggered. wdyt?

re: image name, image name doesn't need to change, `collector` image does collection. this is only for pod name.

**Comment by pie-r** [comment]
@sozercan A label is enough.
I wrote collector image, but instead I want to highlight to the `eraser` image:
```
Image:         mcr.microsoft.com/oss/eraser/eraser:v1.0.0
```
If the `eraser` container becomes `remover`, also the image should reflect the same change for consistency. Do you agree?
```
Image:         mcr.microsoft.com/oss/eraser/remover:v1.0.0
```

**Comment by pie-r** [comment]
@sozercan A label is enough.
I wrote collector image, but instead I want to highlight to the `eraser` image:
```
Image:         mcr.microsoft.com/oss/eraser/eraser:v1.0.0
```
If the `eraser` container becomes `remover`, also the image should reflect the same change for consistency. Do you agree?
```
Image:         mcr.microsoft.com/oss/eraser/remover:v1.0.0
```
