### ISSUE TITLE
Compatible with multiple vulnerability scanners?

### ISSUE THREAD

**Issue by smartaquarius10** [eraser-dev/eraser#467]
Hello Team,

Any plans to make this tool compatible with different scanners for eg. prisma cloud. For eg. infuse any design pattern for making this tool generic enough so that it can integrate with different scanners.

Kind Regards,
Tanul

**Comment by pmengelbert** [comment]
Hi Tanul, thanks for your feedback. The container image for the scanner is interchangeable. Therefore, if you create a new container image running Prisma inside, you could use Prisma as the scanner.

The relevant architecture is here:

![Eraser Architecture](https://azure.github.io/eraser/docs/img/eraser_timer.png)

Currently, communication between the collector -> scanner, (and scanner -> eraser) happens via named pipes on the filesystem, with well-known names for the input and output files. Let me know if you have any more questions -- having an interchangeable scanner is one of the design goals of eraser and feedback/contribution is encouraged.

**Comment by smartaquarius10** [comment]
@pmengelbert Thanks for sharing. Actually, we have prisma cloud hosted across enterprise.. We can't host it on our own in the container.

**Comment by salaxander** [comment]
Closing as stale. Template repo for new scanner plugins can be found [here](https://github.com/Azure/eraser-scanner-template/)
