### ISSUE TITLE
Update Trivy to scan local images

### ISSUE THREAD

**Issue by salaxander** [eraser-dev/eraser#470]
**Describe the solution you'd like**
Trivy currently scans images from a registry rather than using locally cached images

**Trivy PR**: https://github.com/aquasecurity/trivy/pull/3075

**Comment by pmengelbert** [comment]
@salaxander @sozercan [trivy #3075](https://github.com/aquasecurity/trivy/pull/3075) got merged. It should be included in v0.35.0 of Trivy. Not sure of their release cadence, so let's keep this open until its included in the release.

**Comment by sozercan** [comment]
it is currently due Nov 27: https://github.com/aquasecurity/trivy/milestone/11

**Comment by sozercan** [comment]
@pmengelbert good to close?
