### ISSUE TITLE
eraser-controller-manager pod OOMKilled

### ISSUE THREAD

**Issue by amrashwan** [eraser-dev/eraser#487]
**What steps did you take and what happened:**
We enabled image-cleaner on AKS cluster
we can see the eraser-controller-manager pod is CrashLoopBackOff 

    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled

**What did you expect to happen:**
the pod created correctly

**Anything else you would like to add:**
increase the memory limit from 30m to 50m

**Environment:**

- Eraser version: 0.40.0
- Kubernetes version: (use `kubectl version`): Azure Kubernetes KAS1.24.6

**Comment by sozercan** [comment]
Closing this, this is possible by adjusting Helm values. Please see https://github.com/Azure/eraser/blob/c2682a80404cb3587b4f0054702b08ca8033b993/charts/eraser/values.yaml

**Comment by ktumu0225** [comment]
@sozercan There should be a way to change the resource request/limits values while enabling image-cleaner on the cluster though following the instructions here using azure cli or via resource manager api call when being managed via terraform.

https://learn.microsoft.com/en-us/azure/aks/image-cleaner?tabs=azure-cli

The workaround we implemented as of now is to edit the yaml from the backend in the kube-system namespace for eraser controller manager pod.

**Comment by halittiryaki** [comment]
> Closing this, this is possible by adjusting Helm values. Please see https://github.com/Azure/eraser/blob/c2682a80404cb3587b4f0054702b08ca8033b993/charts/eraser/values.yaml

there is no helm install involved as pointed out by @ktumu0225.

created the issue in the AKS repo: [5376](https://github.com/Azure/AKS/issues/5376)
