### ISSUE TITLE
Add global imagePullSecrets setting

### ISSUE THREAD

**Issue by amrashwan** [eraser-dev/eraser#492]
**Describe the solution you'd like**
Add support for a global imagePullSecrets setting to allow all images to pull from private registries using secret.

**Environment:**

- Eraser version: v0.5.0
- Kubernetes version: (use `kubectl version`): 1.24.6

**Comment by sozercan** [comment]
@amrashwan are referring to hosting eraser-related images (manager, collector, scanner, eraser) in a private registry and using pull secrets to pull them?

**Comment by amrashwan** [comment]
Yes exactly, i need to pull the 4 images from my private registry using pull secret

**Comment by pmengelbert** [comment]
I think it makes the most sense to provide this as an option in the helm chart
