### ISSUE TITLE
securityContext for collector pod

### ISSUE THREAD

**Issue by amrashwan** [eraser-dev/eraser#494]
**What steps did you take and what happened:**
I'm trying to install eraser helm chart and the controller is not allowed to create the 3 containers (collector/scanner/eraser) due to an azure policy that prevent the containers from running if  securityContext/runAsNonRoot is not true or readOnlyRootFilesystem is not true

for the 3 containers (collector/scanner/eraser), What is the secuirtycontext requirements for runAsNonRoot/readOnlyRootFilesystem? 

{"level":"error","ts":1669953279.2390826,"msg":"Reconciler error","controller":"imagejob-controller","object":{"name":"imagejob-hpz62"},"namespace":"","name":"imagejob-hpz62","reconcileID":"2c88118e-989d-4a4e-9ba4-075cfcd57486","error":"reconcile new: admission webhook \"validation.gatekeeper.sh\" denied the request: [azurepolicy-k8sazurev3allowedusersgroups-973561909fcec555702f] Container collector is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0\n[azurepolicy-k8sazurev3allowedusersgroups-973561909fcec555702f] Container eraser is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0\n[azurepolicy-k8sazurev3allowedusersgroups-973561909fcec555702f] Container trivy-scanner is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0\n[azurepolicy-k8sazurev3hostfilesystem-bdd7861e251772982eff] HostPath volume {\"hostPath\": {\"path\": \"/run/containerd/containerd.sock\", \"type\": \"\"}, \"name\": \"containerd-sock-volume\"} is not allowed, pod: collector-aks-linux1-27983059-vmss000000-d7ls6. Allowed path: [{\"pathPrefix\": \"/var/lib/kubelet/device-plugins\", \"readOnly\": false}, {\"pathPrefix\": \"/usr/local/nvidia\", \"readOnly\": false}, {\"pathPrefix\": \"/var/log\", \"readOnly\": false}, {\"pathPrefix\": \"/var/tail-db/\", \"readOnly\": false}, {\"pathPrefix\": \"/var/lib/docker/containers\", \"readOnly\": true}, {\"pathPrefix\": \"/etc/machine-id\", \"readOnly\": true}, {\"pathPrefix\": \"/ProgramData/docker/containers\", \"readOnly\": false}, {\"pathPrefix\": \"/k\", \"readOnly\": false}, {\"pathPrefix\": \"/proc\", \"readOnly\": true}, {\"pathPrefix\": \"/sys\", \"readOnly\": true}, {\"pathPrefix\": \"/\", \"readOnly\": true}, {\"pathPrefix\": \"/mnt\", \"readOnly\": false}]\n[azurepolicy-k8sazurev3readonlyrootfilesyst-76e49796d574f9db498c] Readonly root filesystem is required for container. pod:'collector-aks-linux1-27983059-vmss000000-d7ls6', container:'collector'\n[azurepolicy-k8sazurev3readonlyrootfilesyst-76e49796d574f9db498c] Readonly root filesystem is required for container. pod:'collector-aks-linux1-27983059-vmss000000-d7ls6', container:'eraser'\n[azurepolicy-k8sazurev3readonlyrootfilesyst-76e49796d574f9db498c] Readonly root filesystem is required for container. pod:'collector-aks-linux1-27983059-vmss000000-d7ls6', container:'trivy-scanner'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version: v0.5.0
- Kubernetes version: (use `kubectl version`): v1.24.6

**Comment by sozercan** [comment]
@amrashwan it might be okay to set readOnlyRootFilesystem, however, eraser cannot run as non-root as it talks to CRI. If you have this policy as a requirement, eraser must be exempt from this.

**Comment by sozercan** [comment]
partially addressed in #496
