### ISSUE TITLE
collector pod don't run on all nodes

### ISSUE THREAD

**Issue by amrashwan** [eraser-dev/eraser#498]
**What steps did you take and what happened:**
I'm running the eraser but i don't see the collector pod running on all the cluster nodes

k get po
NAME                                             READY   STATUS      RESTARTS   AGE
collector-aks-linux1-27983059-vmss000000-dm2n8   0/3     Completed   0          2m2s
collector-aks-linux1-27983059-vmss000001-xtbzb   0/3     Completed   0          2m2s
collector-aks-system-18979628-vmss000000-6tkj5   0/3     Completed   0          2m2s
eraser-controller-manager-77dbbbdf47-zpc58       1/1     Running     0          2m7s

on windows nodes there is a good description why it failed to run
`{"level":"info","ts":1670254961.1941895,"logger":"controller","msg":"node will be skipped because it matched the specified labels","process":"imagejob-controller","node":"akswin1000000","nodeName":"akswin1000000","labels":{"agentpool":"win1","beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"Standard_D4ds_v4","beta.kubernetes.io/os":"windows","failure-domain.beta.kubernetes.io/region":"eastus","failure-domain.beta.kubernetes.io/zone":"0","kubernetes.azure.com/agentpool":"win1","kubernetes.azure.com/cluster":"xinfra-ci-xinfra-5601-aks-resources","kubernetes.azure.com/kubelet-identity-client-id":"33f3876c-0423-4b77-bb80-be5e28c052c6","kubernetes.azure.com/mode":"user","kubernetes.azure.com/node-image-version":"AKSWindows-2019-containerd-17763.3650.221110","kubernetes.azure.com/os-sku":"Windows2019","kubernetes.azure.com/role":"agent","kubernetes.azure.com/storageprofile":"managed","kubernetes.azure.com/storagetier":"Premium_LRS","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"akswin1000000","kubernetes.io/os":"windows","kubernetes.io/role":"agent","node-role.kubernetes.io/agent":"","node.kubernetes.io/instance-type":"Standard_D4ds_v4","node.kubernetes.io/windows-build":"10.0.17763","storageprofile":"managed","storagetier":"Premium_LRS","topology.disk.csi.azure.com/zone":"","topology.kubernetes.io/region":"eastus","topology.kubernetes.io/zone":"0"},"specifiedSelectors":["eraser.sh/cleanup.filter","kubernetes.io/os=windows"]}
`

but in linux nodes, the logs has no debug info to investigate why it is failed and what pod failed 
`
{"level":"info","ts":1670254961.2809694,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-xinfra-11501615-vmss000000","nodeName":"aks-xinfra-11501615-vmss000000"}
{"level":"info","ts":1670254961.332351,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-linux1-27983059-vmss000001","nodeName":"aks-linux1-27983059-vmss000001"}
{"level":"info","ts":1670254961.3937025,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-xinfra-11501615-vmss000001","nodeName":"aks-xinfra-11501615-vmss000001"}
{"level":"info","ts":1670254961.4478843,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-gpu1-31828253-vmss000001","nodeName":"aks-gpu1-31828253-vmss000001"}
{"level":"info","ts":1670254961.5145497,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-xinfra-11501615-vmss000004","nodeName":"aks-xinfra-11501615-vmss000004"}
{"level":"info","ts":1670254961.5665963,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-system-18979628-vmss000000","nodeName":"aks-system-18979628-vmss000000"}
{"level":"info","ts":1670254961.6471517,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-xinfra-11501615-vmss000003","nodeName":"aks-xinfra-11501615-vmss000003"}
{"level":"info","ts":1670254961.710827,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-xinfra-11501615-vmss000002","nodeName":"aks-xinfra-11501615-vmss000002"}
{"level":"info","ts":1670254961.7913318,"logger":"controller","msg":"Started collector pod on node","process":"imagejob-controller","job":"imagejob-x7dnp","node":"aks-linux1-27983059-vmss000000","nodeName":"aks-linux1-27983059-vmss000000"}
{"level":"info","ts":1670255056.9628646,"logger":"controller","msg":"Marking job as failed","process":"imagejob-controller","success ratio":1,"actual ratio":0}
{"level":"info","ts":1670255056.9753232,"logger":"controller","msg":"ImageCollector Reconcile","process":"imagecollector-controller"}
{"level":"info","ts":1670255056.9753802,"logger":"controller",**"msg":"failed phase","process":"imagecollector-controller"}**
{"level":"info","ts":1670255056.9862635,"logger":"controller","msg":"done reconcile","process":"imagecollector-controller"}
{"level":"info","ts":1670255056.9864016,"logger":"controller","msg":"ImageCollector Reconcile","process":"imagecollector-controller"}
{"level":"info","ts":1670255056.9864528,"logger":"controller","msg":"failed phase","process":"imagecollector-controller"}
{"level":"info","ts":1670255056.9864595,"logger":"controller","msg":"Delaying imagejob delete","process":"imagecollector-controller","job":"imagejob-x7dnp","deleteAter":"2022-12-06 15:44:16 +0000 UTC"}
{"level":"info","ts":1670255056.9865017,"logger":"controller","msg":"done reconcile","process":"imagecollector-controller"}`

Here is all the nodes that runs on the cluster
k get nodes
NAME                             STATUS   ROLES   AGE     VERSION
aks-gpu1-31828253-vmss000001     Ready    agent   4d23h   v1.24.6
aks-linux1-27983059-vmss000000   Ready    agent   4d23h   v1.24.6
aks-linux1-27983059-vmss000001   Ready    agent   4d23h   v1.24.6
aks-system-18979628-vmss000000   Ready    agent   4d23h   v1.24.6
aks-xinfra-11501615-vmss000000   Ready    agent   4d23h   v1.24.6
aks-xinfra-11501615-vmss000001   Ready    agent   4d23h   v1.24.6
aks-xinfra-11501615-vmss000002   Ready    agent   4d23h   v1.24.6
aks-xinfra-11501615-vmss000003   Ready    agent   4d23h   v1.24.6
aks-xinfra-11501615-vmss000004   Ready    agent   4d4h    v1.24.6
akswin1000000                    Ready    agent   4d23h   v1.24.6
akswin2000000                    Ready    agent   4d23h   v1.24.6`

**What did you expect to happen:**
to run on all the other Linux nodes

**Environment:**

- Eraser version: 0.5.0
- Kubernetes version: (use `kubectl version`): 1.24.6

**Comment by pmengelbert** [comment]
@amrashwan Can you give a full listing of the nodes in json? i.e. `kubectl get nodes -o json`. That will give us more information to investigate.

Eraser will only run on linux nodes. Off the top of my head, nodes are also filtered by fitness, i.e. they must have the resources required for eraser to run.

Correction: earlier I typed "windows" instead of "linux"

**Comment by sozercan** [comment]
closing this since we are tracking in #503
