### ISSUE TITLE
remove eraser runtime metrics

### ISSUE THREAD

**Issue by ashnamehrotra** [eraser-dev/eraser#502]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version: v0.5.0
- Kubernetes version: (use `kubectl version`):

**Comment by sozercan** [comment]
@ashnamehrotra  can we confirm runtime metrics are part of otel metrics?

**Comment by ashnamehrotra** [comment]
@sozercan they are not a part of otel, but we can change the endpoint when creating the manager to have all the metrics reported in the same place

**Comment by pmengelbert** [comment]
@ashnamehrotra Can this be closed as completed?

**Comment by ashnamehrotra** [comment]
@pmengelbert yes!
