### ISSUE TITLE
add new v1 api

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#505]
**Describe the solution you'd like**
- add new v1 and unversioned api
- generate conversions using [conversion-gen](https://pkg.go.dev/k8s.io/code-generator/cmd/conversion-gen) and add tool to ci (part of `make generate`)
- change code references from v1alpha1 to unversioned 
- keep some tests in v1alpha1 to make sure we are backwards compatible

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
Completed by #544
