### ISSUE TITLE
eraser-trivy-scanner got resources 0 for cpu and memory

### ISSUE THREAD

**Issue by amrashwan** [eraser-dev/eraser#514]
**What steps did you take and what happened:**
    image: mcr.microsoft.com/oss/eraser/eraser-trivy-scanner:v0.5.0
    imagePullPolicy: IfNotPresent
    name: trivy-scanner
    resources:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"

**Environment:**

- Eraser version: v0.5.0
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
These are unset because the scanner might take a lot of memory or CPU depending on how many images are present. They  can be set using helm: 
```bash
helm install <...> \
    --set 'controllerManager.additionalArgs={--scanner-cpu-request=1000m,--scanner-cpu-limit=1500m,--scanner-mem-request=500Mi,--scanner-mem-limit=2Gi}'
```

**Comment by sozercan** [comment]
@amrashwan is this resolved?

**Comment by sozercan** [comment]
@pmengelbert okay to close this with configmap change?

**Comment by pmengelbert** [comment]
> @pmengelbert okay to close this with configmap change?

@sozercan fine by me

**Comment by pmengelbert** [comment]
configurable by #581
