### ISSUE TITLE
collector pods no longer running in parallel

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#537]
**What steps did you take and what happened:**
The collector pods are now running one-at-a-time instead of all-at-once. This appears to be related to the changes in #515 . We probably need to take action asynchronously when each pod becomes ready.

- Eraser version: v1.0.0-beta.1
- Kubernetes version: (use `kubectl version`):

**Comment by ashnamehrotra** [comment]
fixed in #546
