### ISSUE TITLE
Release PR workflow should be idempotent

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#610]
**What steps did you take and what happened:**
- Run the create_release_pull_request action such that it fails during the manifest or doc generation
- Fix the cause of the failure and get it merged into main
- Trigger the create_release_pull_request job again

**What did you expect to happen:**
I expect the create_release_pull_request option to reset the already existing branch to the updated main branch before proceeding with the release

**Anything else you would like to add:**

**Environment:**

- Eraser version: v1.0.0-beta.3

**Comment by sozercan** [comment]
No longer applicable since we can't use this workflow anymore. Closing for now

related #642
