### ISSUE TITLE
remove config reference to webhook from helm chart

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#613]
**What steps did you take and what happened:**
since we don't have a webhook, this might be confusing to folks

can we remove this flag from helm chart?

https://github.com/Azure/eraser/blob/main/manifest_staging/charts/eraser/values.yaml#L6-L7

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
Technically part of the `ControllerManagerConfigurationSpec`, so can't be removed from the config struct, but can be removed from the helm chart

**Comment by sozercan** [comment]
thanks! clarified in the issue

**Comment by sozercan** [comment]
Closed in #708
