### ISSUE TITLE
resolve docusaurus vulnerabilities using yarn resolutions

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#615]
**Describe the solution you'd like**
similar to https://github.com/project-copacetic/copacetic/pull/27

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by inFocus7** [comment]
Could I pick this up?

The vulnerability fix has [yet to be backported](https://github.com/facebook/docusaurus/pull/8660#issuecomment-1497792419) to [v2](https://github.com/facebook/docusaurus/blob/4a2200ace4f7e5e2c5c66ff3a57095cbffc1c540/packages/docusaurus/package.json#L99), so we'll still need to resolve it here as well.

---

I'll push up a PR for now, and if we don't want it we can delete it. It's a very quick update/fix, so will be fastest to just have it up by whenever this gets seen lol
