### ISSUE TITLE
Make containerd.sock configurable in your helm charts

### ISSUE THREAD

**Issue by mdrakiburrahman** [eraser-dev/eraser#647]
Microk8s runs containerd in `/var/snap/microk8s/common/run/containerd.sock`.

Eraser right now hardcodes the containerd socket path as a constant:
https://github.com/Azure/eraser/blob/dce0e838ea638e383ef8d38f68b3b726e64e66bd/pkg/utils/utils.go#L37

Even without Microk8s, this would reduce the usability of eraser in other environments where the socket is installed somewhere else.

This results in Eraser Collector failing in Microk8s:
```bash
{"level":"error","ts":1677250961.0918322,"logger":"eraser","msg":"failed to get image client","error":"rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService\nrpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService","stacktrace":"main.main\n\t/workspace/pkg/eraser/eraser.go:71\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
An easy solution is to expose the Containerd Socket parameter in your Helm chart, and injecting that into Go as a ConfigMap.

**Environment:**

- Eraser version: `kubectl apply -f https://raw.githubusercontent.com/Azure/eraser/v1.0.0/deploy/eraser.yaml`
- Kubernetes version: (use `kubectl version`): Microk8s `v1.26.1`

**Comment by pmengelbert** [comment]
Thanks @mdrakiburrahman . This is on the backlog, it's an issue with `k3s` as well.

**Comment by sozercan** [comment]
Should be unblocked by #656

**Comment by onedr0p** [comment]
Any update on this?

**Comment by pmengelbert** [comment]
@onedr0p We have @ashnamehrotra picking up on this, so someone will be actively working on it again. Thanks for the bump!
