### ISSUE TITLE
collector pods stuck in Error state 

### ISSUE THREAD

**Issue by arashwanns** [eraser-dev/eraser#686]
**What steps did you take and what happened:**
We are getting error state in 2 collector pods  which prevent deletion of the job

collector-aks-linux8b-40047806-vmss00005q-v756n      2/3     Error       0             3d10h
collector-aks-linux8b-40047806-vmss00008m-v584l      2/3     Error       0             3d10h

**Anything else you would like to add:**
k logs po/collector-aks-linux8b-40047806-vmss00008m-v584l -c trivy-scanner
devacrxmix.azurecr.io/mix-api:0.10.0-4.30cb0ed0"],"digests":["sha256:b35bb9b8540bf3c99ae0df9fdebe823174a5541c46fc2511171ef254041fed60"]}}
{"level":"info","ts":1680443983.0649552,"logger":"scanner","msg":"scanning image with id","provider":"trivy","imageID":"sha256:fefecced9723c7aa4be5d958fe7fda58edb8ac2cd00383d12f6b9ded9d6b8a68","refs":["devacrxfabric.azurecr.io/helm/astra-qa-test:1.0.0-gl1313974"]}
{"level":"info","ts":1680443983.0649745,"logger":"scanner","msg":"scanning image with ref","provider":"trivy","ref":"devacrxfabric.azurecr.io/helm/astra-qa-test:1.0.0-gl1313974"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e65816]

goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/fanal/image/daemon.inspect({_, _}, {_, _}, {_, _})
        /go/pkg/mod/github.com/aquasecurity/trivy@v0.35.0/pkg/fanal/image/daemon/containerd.go:242 +0x636
github.com/aquasecurity/trivy/pkg/fanal/image/daemon.ContainerdImage({0x431de88, 0xc00012e000}, {0xc00064b8c0, 0x3b})
        /go/pkg/mod/github.com/aquasecurity/trivy@v0.35.0/pkg/fanal/image/daemon/containerd.go:123 +0x3d3
github.com/aquasecurity/trivy/pkg/fanal/image.tryContainerdDaemon({0x431de88?, 0xc00012e000?}, {0xc00064b8c0, 0x3b})
        /go/pkg/mod/github.com/aquasecurity/trivy@v0.35.0/pkg/fanal/image/daemon.go:36 +0x31
github.com/aquasecurity/trivy/pkg/fanal/image.NewContainerImage({0x431de88, 0xc00012e000}, {0xc00064b8c0, 0x3b}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /go/pkg/mod/github.com/aquasecurity/trivy@v0.35.0/pkg/fanal/image/image.go:90 +0x2fe
main.(*ImageScanner).Scan(0xc00170e800, {{0xc002a975e0, 0x47}, {0xc0006efa80, 0x1, 0x4}, {0x0, 0x0, 0x0}})
        /workspace/pkg/scanners/trivy/types.go:116 +0x4db
main.scan({0x4305100, 0xc00170e800}, {0xc001bad500, 0xbb, 0xd3})
        /workspace/pkg/scanners/trivy/trivy.go:285 +0x1e6
main.main()
        /workspace/pkg/scanners/trivy/trivy.go:160 +0x965

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by arashwanns** [comment]
Hi guys,
any update on this issue
Thanks

**Comment by pmengelbert** [comment]
@arashwanns 
Can you please provide the eraser version, the kubernetes version, and the steps you are taking that produces this error?

Thanks

**Comment by sozercan** [comment]
@arashwanns since `devacrxfabric.azurecr.io/helm/astra-qa-test:1.0.0-gl1313974` is not public, please provide more information about this too

**Comment by sozercan** [comment]
I recall we had an offline discussion with @djsly about this, `astra-qa-test` is an OCI artifact which is causing this issue.
