### ISSUE TITLE
Remove leader election since it is not used

### ISSUE THREAD

**Issue by pmengelbert** [eraser-dev/eraser#697]
Leader election isn't used in Eraser, so it shouldn't be an option in the configmap.

**Environment:**

- Eraser version: v1.0.1-beta.1
- Kubernetes version: (use `kubectl version`):

**Comment by pmengelbert** [comment]
Unfortunately, the field is part of the `ControllerManagerConfigurationSpec` which is a member of the `EraserConfig` struct. I'm not sure if it can be easily removed.

However, I think we can remove it from the helm chart.

**Comment by sozercan** [comment]
related https://github.com/kubernetes-sigs/controller-runtime/blob/f83169592e24f80c1704b4c5bf5022620313a271/pkg/config/config.go#L33
