### ISSUE TITLE
Eraser controller failing to create config map in a private AKS cluster

### ISSUE THREAD

**Issue by sanjaydebnath** [eraser-dev/eraser#750]
**What steps did you take and what happened:**
Create a private aks cluster following https://learn.microsoft.com/en-us/azure/aks/private-clusters
Enable Eraser by following https://learn.microsoft.com/en-us/azure/aks/image-cleaner?tabs=azure-cli#enable-image-cleaner-on-your-aks-cluster (or enable during the initial aks creation as shown below)
Manually deploy 'ImageList' following https://learn.microsoft.com/en-us/azure/aks/image-cleaner?tabs=azure-cli#manually-remove-images
Check logs from 'eraser-controller-manager-xxx' pod

**What did you expect to happen:**
Job should execute cleanup & reconcile. But we see logs like below

_"{"level":"error","ts":1684887610.1327276,"msg":"Reconciler error","controller":"imagelist-controller","object":{"name":"imagelist"},"namespace":"","name":"imagelist","reconcileID":"dcf87049-e79e-4526-851b-fe5a778aec6d","error":"create configmap: configmaps is forbidden: User \"system:serviceaccount:kube-system:eraser-controller-manager\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}_"

**Anything else you would like to add:**
Code to create AKS cluster
````bash
az aks create \
  -n $PRIMARY_AKS_NAME \
  -g $PRIMARY_RG_NAME \
  --attach-acr $ACR_ID \
  --workspace-resource-id $WORKSPACE_ID \
  --disable-local-accounts \
  --disable-public-fqdn \
  --enable-encryption-at-host \
  --enable-secret-rotation \
  --enable-private-cluster \
  --enable-managed-identity \
  --enable-aad \
  --enable-keda \
  --enable-workload-identity \
  --enable-oidc-issuer \
  --enable-image-cleaner --image-cleaner-interval-hours 24 \
  --enable-addons azure-keyvault-secrets-provider,monitoring \
  --enable-apiserver-vnet-integration \
  --enable-msi-auth-for-monitoring \
  --rotation-poll-interval 15m \
  --assign-identity $AKS_AGENTPOOL_IDENTITY_ID \
  --assign-kubelet-identity $AKS_KUBELET_IDENTITY_ID \
  --aad-admin-group-object-ids $APPDEV_GR_ID \
  --aad-tenant-id $APPDEV_GR_TENANT_ID \
  --vnet-subnet-id $PRIMARY_AKS_NODE_SUBNET_ID \
  --apiserver-subnet-id $PRIMARY_AKS_API_SERVER_SUBNET_ID \
  --network-plugin azure \
  --network-policy azure \
  --outbound-type userDefinedRouting \
  --generate-ssh-keys \
  --kubernetes-version 1.25.5 \
  --node-vm-size $PRIMARY_DEFAULT_NODE_SIZE \
  --node-osdisk-size $DEFAULT_NODE_DISK_SIZE \
  --nodepool-name $DEFAULT_NODE_POOL_NAME \
  --os-sku Mariner \
  --vm-set-type VirtualMachineScaleSets \
  --auto-upgrade-channel node-image \
  --zones 1 2 3 \
  --enable-cluster-autoscaler \
  --min-count $MIN_SYSTEM_NODE_COUNT \
  --max-count $MAX_SYSTEM_NODE_COUNT \
  -l $LOCATION
````

**Environment:**

- Eraser version: latest
- Kubernetes version: (use `kubectl version`): 1.26.3

**Comment by sozercan** [comment]
@sanjaydebnath thanks for filing an issue! since this is an issue for the AKS image cleaner addon, please open an issue in https://github.com/Azure/AKS

I believe this was due to a config bug in AKS, which was fixed now.
cc @jiashun0011
