### ISSUE TITLE
Add trivy scan on git repository and on eraser images

### ISSUE THREAD

**Issue by ritazh** [eraser-dev/eraser#781]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Example:
https://github.com/open-policy-agent/gatekeeper/blob/master/.github/workflows/workflow.yaml#L314-L352
https://github.com/open-policy-agent/gatekeeper/pull/2169

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by ashnamehrotra** [comment]
trivy scan for eraser images here: https://github.com/Azure/eraser/blob/3febb3a2f1345812d7b17071c700fc30ceaf398e/.github/workflows/test.yaml#L137C1-L186

**Comment by ashnamehrotra** [comment]
created issue #783 to track trivy scan results more frequently
