### ISSUE TITLE
Eraser cannot be scheduled on tainted nodes

### ISSUE THREAD

**Issue by sarahecraddock** [eraser-dev/eraser#785]
**What steps did you take and what happened:**
We are using taints on our node pools. After deployment of eraser via bicep, the eraser pods are failing to schedule on any of our node pools with the following error:
<img width="1187" alt="image" src="https://github.com/Azure/eraser/assets/61050444/8b261e03-80d7-4dc0-9861-34dc9601648e">
It appears that the eraser pod default tolerations are not working to enable it to be scheduled on tainted nodes.
<img width="761" alt="image" src="https://github.com/Azure/eraser/assets/61050444/6879febe-5f37-4db1-9748-ad213ebb58c1">

**What did you expect to happen:**
I would expect the eraser pods to schedule successfully on all nodes, as per this [previous closed issue](https://github.com/Azure/eraser/issues/503).

**Anything else you would like to add:**

**Environment:**
- Eraser version: mcr.microsoft.com/oss/eraser/eraser-manager:v1.1.0
- Kubernetes version: (use `kubectl version`): 1.26.3
- Deployed via bicep (AKS security profile config):
   <img width="192" alt="image" src="https://github.com/Azure/eraser/assets/61050444/7b861b54-90d0-4006-a4f0-6759a3ab69b8">

**Comment by sozercan** [comment]
@sarahecraddock previous issue was for the worker (eraser) pods, looks like this is controller (eraser-controller-manager) pod.

this looks like an AKS specific issue. @jiashun0011 does AKS need to add this toleration to the addon?

**Comment by sarahecraddock** [comment]
@sozercan @jiashun0011 Any updates on this?

**Comment by sozercan** [comment]
Closing this since this an AKS addon-specific issue, not OSS. Please open an issue in https://github.com/azure/aks
