### ISSUE TITLE
support for trivy status

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#821]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

allow filtering by vuln status

https://aquasecurity.github.io/trivy/v0.44/docs/configuration/filtering/#by-status

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by inFocus7** [comment]
Hi! 👋🏼 Was this planned to be picked up by someone else (**sozercan**) or could I? 
I see it's on the 1.4 milestone, ~with latest LTS release being 1.2, so not sure if this is planned to just be left until the time comes.~ for December 2023 on the public roadmap.

If I can pick it up, it looks not too bad. I'm thinking of updating the helm template to allow for an extra field
```yaml
ignoredStatuses:
# - will_not_fix
# - <... + other ones from the trivy filter page>
```

then updating our Trivy CLI go code to use the above values as its arguments to `--ignore-status <ignoredStatuses,>`

---

Ah actually looks like `scanner.config` has a multiline string with `vulnerabilities` under it, so may not update helm template, but whatever parses it to get the new `ignoredStatuses` field idea.

**Comment by sozercan** [comment]
@inFocus7 hello! 👋 we would love the contribution!

This would be a similar type of field as these (types, security checks, severities) in the configmap: https://github.com/eraser-dev/eraser/blob/7cdb6eb5a14eece9a2b35a19d0485067e8728318/pkg/scanners/trivy/types.go#L74-L79 and depending on the user specified values it'll ignore those statuses (such as `not_affected`). https://github.com/eraser-dev/eraser/blob/7cdb6eb5a14eece9a2b35a19d0485067e8728318/pkg/scanners/trivy/types.go#L118-L131

Please let me know if this answers your question and gives you info to get started.

**Comment by inFocus7** [comment]
Awesome, thank you! 

I just put up a draft PR that I worked on yesterday. I'll still need to manually test that it acts as expected before being confident enough to un-draft it 👍🏼

**Comment by inFocus7** [comment]
I'd say I'm _very_ close to the finish line. I manually verified it and added my verification steps on the PR. 

A final question/unknown is: Did I update every relevant area to expose `ignoredStatuses` both dev & user-facing?
