### ISSUE TITLE
Update Eraser logo used in docs header

### ISSUE THREAD

**Issue by inFocus7** [eraser-dev/eraser#847]
The [Eraser docs](https://eraser-dev.github.io/eraser/docs/) are still using 🧹 as the logo, although we are now using a [new logo](https://avatars.githubusercontent.com/u/122392306?s=200&v=4). 
The logo is defined in the code [here](https://github.com/eraser-dev/eraser/blob/7cdb6eb5a14eece9a2b35a19d0485067e8728318/docs/docusaurus.config.js#L57-L60).

Note: I couldn't find an existing `png`/`jpg` of the new logo, so we'll need to add an image to the project as well.

**Comment by inFocus7** [comment]
Haven't looked into the landscape codebase much, and this is better requested in that repo, but also worth updating the Eraser logo in Landscape. It's currently the default image.

- [current view](https://landscape.cncf.io/card-mode?selected=eraser)
- [default logo in code](https://github.com/cncf/landscape/blob/master/hosted_logos/eraser.svg)

**Comment by salaxander** [comment]
Thanks for opening! We're waiting on CNCF to finalize on the logo on their end, though they've provided us with the PNG. Once they close our service desk ticket we'll get it added to CNCF/artwork which should propagate to landscape

**Comment by salaxander** [comment]
Everything has been merged now :). Should correctly show on the CNCF website shortly.
