### ISSUE TITLE
fix extra if in deploy docs action

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#853]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
remove extra `if`

https://github.com/eraser-dev/eraser/blame/59533c262b0f467fc43056c35ce1b13c2c18c09f/.github/workflows/deploy_docs.yaml#L60

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by inFocus7** [comment]
Can I pick this up? 👀

**Comment by sozercan** [comment]
@inFocus7 thanks! assigned to you

**Comment by inFocus7** [comment]
Thank you, just pushed up the update!
