### ISSUE TITLE
add a release process doc

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#869]
**Describe the solution you'd like**
a release process doc that's similar to https://github.com/open-policy-agent/gatekeeper/blob/master/docs/RELEASE.md for maintainers

should have step by step instructions to create a new release

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

**Comment by ashnamehrotra** [comment]
we documented release process here: https://github.com/eraser-dev/eraser/blob/main/docs/versioned_docs/version-v1.2.x/releasing.md
