### ISSUE TITLE
[REQ] I hope to abstract EraserConfig into a K8S CRD

### ISSUE THREAD

**Issue by gitlayzer** [eraser-dev/eraser#936]
### What kind of request is this?

New feature

### What is your request or suggestion?

I hope to abstract EraserConfig into a K8S CRD，This avoids frequent changes ConfigMap

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by pmengelbert** [comment]
@gitlayzer What is the reason for this proposed change? We have the EraserConfig as a configmap already.

**Comment by gitlayzer** [comment]
> @gitlayzer提出这一变更的原因是什么？我们已经将 EraserConfig 作为配置映射。

I know you are talking about the ConfigMap method, but according to the concept of K8S, we actually prefer to be able to operate the configuration in the form of CRD, so that we can avoid frequent modification of the configmap. The second is to look at the configuration of the ancient EraserConfig in Shanshan District. Is it designed to be a CRD itself?

**Comment by sozercan** [comment]
@gitlayzer we don't have any plans to convert configmap to a CRD at this time. While having a CRD can have useful for validation, it is a overhead for simple configuration.

If you are interested in design and implementation, it would be great if you can start a design doc including migrating existing users from configmap to crd. Once you are done, we can review the design in the community call.

**Comment by gitlayzer** [comment]
@sozercan Got it, thank you for your answer
