### ISSUE TITLE
[REQ] Remove unused images as part of regular clean up job?

### ISSUE THREAD

**Issue by sebader** [eraser-dev/eraser#977]
### What kind of request is this?

Other

### What is your request or suggestion?

How can we include removal of unused images (https://github.com/eraser-dev/eraser/pull/84) in the regular cleanup job which by default only removes images with known vulnerabilities/EOL? 

(We're using Eraser on AKS)

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by pmengelbert** [comment]
@sebader This is actually already possible by disabling the scanner. If you are deploying using the helm chart, you can set

```yaml
runtimeConfig:
  components:
    scanner:
      enabled: false
```

If you are deploying some other way, you can modify the analogous place in the configmap.

The reason this works is we have the collector (find unused images) -> scanner (filter down to vuln images) -> remover (remove what's left after filter).  By removing the scanner, the pipeline becomes collector -> remover, which will just remove all the unused images.
