### ISSUE TITLE
[REQ] docs: mention disabling scanner will remove all images

### ISSUE THREAD

**Issue by sozercan** [eraser-dev/eraser#978]
### What kind of request is this?

Other

### What is your request or suggestion?

I don't believe this is mentioned anywhere. If so, we can close this

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by akhilsaivenkata** [comment]
Hi @sozercan , I am new to this community and I am looking forward to starting my journey with this project. Would it be fine 
if I take this up?

**Comment by akhilsaivenkata** [comment]
Hi @sozercan , Could you please describe this issue more.. like where should i make the change and what sort of change is required in the documentation?

**Comment by sozercan** [comment]
@akhilsaivenkata thank you for the interest! please feel free to pick this up.

context for the issue:
If you don't enable the scanner component via the helm chart with `runtimeConfig.components.scanner` (https://github.com/eraser-dev/eraser/blob/main/charts/eraser/README.md) or manually in the yaml, eraser, by default, will remove all non-running images. we are missing to mention this in the docs.

this'll be an addition to the https://eraser-dev.github.io/eraser/docs/customization page.
https://github.com/eraser-dev/eraser/blob/main/docs/docs/customization.md
please make sure to update the versioned_docs too (at least for the `1.3.x`): https://github.com/eraser-dev/eraser/blob/main/docs/versioned_docs/version-v1.3.x/customization.md

**Comment by akhilsaivenkata** [comment]
Thank you so much @sozercan for your help!!!

**Comment by akhilsaivenkata** [comment]
\assign

**Comment by akhilsaivenkata** [comment]
@sozercan , can you please check this piece of modification. If it looks good then I will proceed with other versions as well and push the code.

`### Configuring Components

An _ImageJob_ is made up of various sub-jobs, with one sub-job for each node.
These sub-jobs can be broken down further into three stages.
1. Collection (What is on the node?)
1. Scanning (What images conform to the policy I've provided?)
1. Removal (Remove images based on the results of the above)

Of the above stages, only Removal is mandatory. The others can be disabled.
Furthermore, manually triggered _ImageJobs_ will skip right to removal, even if
Eraser is configured to collect and scan. Collection and Scanning will only
take place when:
1. The collector and/or scanner `components` are enabled, AND
1. The job was *not* triggered manually by creating an _ImageList_.

Disabling scanner will remove all non-running images by default.
### Swapping out components`
