### ISSUE TITLE
Do multiple ImageList make sense?

### ISSUE THREAD

**Issue by cpuguy83** [eraser-dev/eraser#98]
Do we really need to have a CRD for imagelists?
Thinking about it, it seems strange that we'd maintain separate lists whereas a single config map could solve this problem.
To add an item to the list, update the config map. When the configmap is updated we can trigger a reconcile.

Using a config map also has the added benefit of giving us something we can just mount into the eraser pod as a volume for it to get the image list itself.

Managing multiple lists also seems a bit hairy to deal with.

**Comment by cpuguy83** [comment]
We _could_ also treat the imagelist like a point-in-time execution of what is in a configmap (or other some source of truth).

**Comment by sozercan** [comment]
Would it make sense to create a single instance of ImageList? I am not sure if I can think about a use case for multiple imagelists.

**Comment by sozercan** [comment]
Potential use case: multiple scanner implementations can generate different lists, instead of clobbering each other (or us having to deal with merges).

For simplicity, I think we can go for a single instance for ImageList for now.

**Comment by cpuguy83** [comment]
Yes, continuing to use a well-defined type does have benefits.

**Comment by ritazh** [comment]
+1 for a single instance of ImageList
