### ISSUE TITLE
[REQ] Support for extra volume mount in eraser pod

### ISSUE THREAD

**Issue by jiashun0011** [eraser-dev/eraser#996]
### What kind of request is this?

New feature

### What is your request or suggestion?

When using eraser in private cloud, we may need mount extra certs to download trivy-db to ensure eraser scanner work as expected.

Currently, eraser pod's lifecycle is controlled by controller manager which means there is no workaround to mount the certs permanently for eraser pod.

Can you help provide some fields in `controller_manager_config.yaml` where we can define the certs to mount then you can mount them during eraser pod's creation?

### Are you willing to submit PRs to contribute to this feature request?

- [X] Yes, I am willing to implement it.

**Comment by ashnamehrotra** [comment]
@jiashun0011 there are no fields within `controller_manager_config.yaml `currently that take in certificates. If you need to mount the certs during eraser pods creation, you would need to pass the value to the [manager](https://github.com/eraser-dev/eraser/blob/main/config/manager/controller_manager_config.yaml#L3-L26) by creating a new field, and retrieve it in `createImageJob` function.
